# Generated by Django 6.0 on 2025-12-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ready to ship', 'Ready to ship'), ('Not paid', 'Not paid'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], default='Not paid', max_length=20),
        ),
    ]
