# Generated by Django 6.0 on 2025-12-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Shipped', 'Shipped'), ('Ready to ship', 'Ready to ship'), ('Delivered', 'Delivered'), ('Not paid', 'Not paid')], default='Not paid', max_length=20),
        ),
    ]
