# Generated by Django 6.0 on 2025-12-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_total_price_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Not paid', 'Not paid'), ('Ready to ship', 'Ready to ship'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Not paid', max_length=20),
        ),
    ]
