# Generated by Django 6.0 on 2025-12-27 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Ready to ship', 'Ready to ship'), ('Not paid', 'Not paid'), ('Canceled', 'Canceled'), ('Shipped', 'Shipped')], default='Not paid', max_length=20),
        ),
    ]
