# Generated by Django 6.0 on 2025-12-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
