# Generated by Django 6.0 on 2025-12-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_review_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
